{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bagshop-catalog.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bagshop-catalog.name" . }}
    helm.sh/chart: {{ include "bagshop-catalog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: 8083
    host: {{ .Values.ingress.host }}
{{- end }}
