apiVersion: v1
kind: Service
metadata:
  name: {{ include "bagshop-catalog.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "bagshop-catalog.name" . }}-db
    helm.sh/chart: {{ include "bagshop-catalog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 3306
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "bagshop-catalog.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bagshop-catalog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bagshop-catalog.name" . }}
    helm.sh/chart: {{ include "bagshop-catalog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8083
  selector:
    app.kubernetes.io/name: {{ include "bagshop-catalog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
